<?php
/**
 * StoreNodeRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Pelican\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Prepaid-Host - Gameserver
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Pelican\Client\Model;

use \ArrayAccess;
use \Pelican\Client\ObjectSerializer;

/**
 * StoreNodeRequest Class Doc Comment
 *
 * @category Class
 * @package  Pelican\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StoreNodeRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StoreNodeRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'name' => 'string',
        'description' => 'string',
        'public' => 'bool',
        'fqdn' => 'string',
        'scheme' => 'string',
        'behind_proxy' => 'bool',
        'memory' => 'float',
        'memory_overallocate' => 'float',
        'disk' => 'float',
        'disk_overallocate' => 'float',
        'cpu' => 'float',
        'cpu_overallocate' => 'float',
        'daemon_base' => 'string',
        'daemon_sftp' => 'float',
        'daemon_sftp_alias' => 'string',
        'daemon_listen' => 'float',
        'daemon_connect' => 'float',
        'maintenance_mode' => 'bool',
        'upload_size' => 'int',
        'tags' => 'string[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'name' => null,
        'description' => null,
        'public' => null,
        'fqdn' => null,
        'scheme' => null,
        'behind_proxy' => null,
        'memory' => null,
        'memory_overallocate' => null,
        'disk' => null,
        'disk_overallocate' => null,
        'cpu' => null,
        'cpu_overallocate' => null,
        'daemon_base' => null,
        'daemon_sftp' => null,
        'daemon_sftp_alias' => null,
        'daemon_listen' => null,
        'daemon_connect' => null,
        'maintenance_mode' => null,
        'upload_size' => null,
        'tags' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'name' => false,
        'description' => true,
        'public' => false,
        'fqdn' => false,
        'scheme' => false,
        'behind_proxy' => false,
        'memory' => false,
        'memory_overallocate' => false,
        'disk' => false,
        'disk_overallocate' => false,
        'cpu' => false,
        'cpu_overallocate' => false,
        'daemon_base' => false,
        'daemon_sftp' => false,
        'daemon_sftp_alias' => true,
        'daemon_listen' => false,
        'daemon_connect' => false,
        'maintenance_mode' => false,
        'upload_size' => false,
        'tags' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'name' => 'name',
        'description' => 'description',
        'public' => 'public',
        'fqdn' => 'fqdn',
        'scheme' => 'scheme',
        'behind_proxy' => 'behind_proxy',
        'memory' => 'memory',
        'memory_overallocate' => 'memory_overallocate',
        'disk' => 'disk',
        'disk_overallocate' => 'disk_overallocate',
        'cpu' => 'cpu',
        'cpu_overallocate' => 'cpu_overallocate',
        'daemon_base' => 'daemon_base',
        'daemon_sftp' => 'daemon_sftp',
        'daemon_sftp_alias' => 'daemon_sftp_alias',
        'daemon_listen' => 'daemon_listen',
        'daemon_connect' => 'daemon_connect',
        'maintenance_mode' => 'maintenance_mode',
        'upload_size' => 'upload_size',
        'tags' => 'tags'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'name' => 'setName',
        'description' => 'setDescription',
        'public' => 'setPublic',
        'fqdn' => 'setFqdn',
        'scheme' => 'setScheme',
        'behind_proxy' => 'setBehindProxy',
        'memory' => 'setMemory',
        'memory_overallocate' => 'setMemoryOverallocate',
        'disk' => 'setDisk',
        'disk_overallocate' => 'setDiskOverallocate',
        'cpu' => 'setCpu',
        'cpu_overallocate' => 'setCpuOverallocate',
        'daemon_base' => 'setDaemonBase',
        'daemon_sftp' => 'setDaemonSftp',
        'daemon_sftp_alias' => 'setDaemonSftpAlias',
        'daemon_listen' => 'setDaemonListen',
        'daemon_connect' => 'setDaemonConnect',
        'maintenance_mode' => 'setMaintenanceMode',
        'upload_size' => 'setUploadSize',
        'tags' => 'setTags'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'name' => 'getName',
        'description' => 'getDescription',
        'public' => 'getPublic',
        'fqdn' => 'getFqdn',
        'scheme' => 'getScheme',
        'behind_proxy' => 'getBehindProxy',
        'memory' => 'getMemory',
        'memory_overallocate' => 'getMemoryOverallocate',
        'disk' => 'getDisk',
        'disk_overallocate' => 'getDiskOverallocate',
        'cpu' => 'getCpu',
        'cpu_overallocate' => 'getCpuOverallocate',
        'daemon_base' => 'getDaemonBase',
        'daemon_sftp' => 'getDaemonSftp',
        'daemon_sftp_alias' => 'getDaemonSftpAlias',
        'daemon_listen' => 'getDaemonListen',
        'daemon_connect' => 'getDaemonConnect',
        'maintenance_mode' => 'getMaintenanceMode',
        'upload_size' => 'getUploadSize',
        'tags' => 'getTags'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const SCHEME_HTTP = 'http';
    public const SCHEME_HTTPS = 'https';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSchemeAllowableValues()
    {
        return [
            self::SCHEME_HTTP,
            self::SCHEME_HTTPS,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('public', $data ?? [], null);
        $this->setIfExists('fqdn', $data ?? [], null);
        $this->setIfExists('scheme', $data ?? [], null);
        $this->setIfExists('behind_proxy', $data ?? [], null);
        $this->setIfExists('memory', $data ?? [], null);
        $this->setIfExists('memory_overallocate', $data ?? [], null);
        $this->setIfExists('disk', $data ?? [], null);
        $this->setIfExists('disk_overallocate', $data ?? [], null);
        $this->setIfExists('cpu', $data ?? [], null);
        $this->setIfExists('cpu_overallocate', $data ?? [], null);
        $this->setIfExists('daemon_base', $data ?? [], null);
        $this->setIfExists('daemon_sftp', $data ?? [], null);
        $this->setIfExists('daemon_sftp_alias', $data ?? [], null);
        $this->setIfExists('daemon_listen', $data ?? [], null);
        $this->setIfExists('daemon_connect', $data ?? [], null);
        $this->setIfExists('maintenance_mode', $data ?? [], null);
        $this->setIfExists('upload_size', $data ?? [], null);
        $this->setIfExists('tags', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 100)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 100.";
        }

        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['fqdn'] === null) {
            $invalidProperties[] = "'fqdn' can't be null";
        }
        if ($this->container['scheme'] === null) {
            $invalidProperties[] = "'scheme' can't be null";
        }
        $allowedValues = $this->getSchemeAllowableValues();
        if (!is_null($this->container['scheme']) && !in_array($this->container['scheme'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'scheme', must be one of '%s'",
                $this->container['scheme'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['memory'] === null) {
            $invalidProperties[] = "'memory' can't be null";
        }
        if (($this->container['memory'] < 0)) {
            $invalidProperties[] = "invalid value for 'memory', must be bigger than or equal to 0.";
        }

        if ($this->container['memory_overallocate'] === null) {
            $invalidProperties[] = "'memory_overallocate' can't be null";
        }
        if (($this->container['memory_overallocate'] < -1)) {
            $invalidProperties[] = "invalid value for 'memory_overallocate', must be bigger than or equal to -1.";
        }

        if ($this->container['disk'] === null) {
            $invalidProperties[] = "'disk' can't be null";
        }
        if (($this->container['disk'] < 0)) {
            $invalidProperties[] = "invalid value for 'disk', must be bigger than or equal to 0.";
        }

        if ($this->container['disk_overallocate'] === null) {
            $invalidProperties[] = "'disk_overallocate' can't be null";
        }
        if (($this->container['disk_overallocate'] < -1)) {
            $invalidProperties[] = "invalid value for 'disk_overallocate', must be bigger than or equal to -1.";
        }

        if ($this->container['cpu'] === null) {
            $invalidProperties[] = "'cpu' can't be null";
        }
        if (($this->container['cpu'] < 0)) {
            $invalidProperties[] = "invalid value for 'cpu', must be bigger than or equal to 0.";
        }

        if ($this->container['cpu_overallocate'] === null) {
            $invalidProperties[] = "'cpu_overallocate' can't be null";
        }
        if (($this->container['cpu_overallocate'] < -1)) {
            $invalidProperties[] = "invalid value for 'cpu_overallocate', must be bigger than or equal to -1.";
        }

        if ($this->container['daemon_sftp'] === null) {
            $invalidProperties[] = "'daemon_sftp' can't be null";
        }
        if (($this->container['daemon_sftp'] > 65535)) {
            $invalidProperties[] = "invalid value for 'daemon_sftp', must be smaller than or equal to 65535.";
        }

        if (($this->container['daemon_sftp'] < 1)) {
            $invalidProperties[] = "invalid value for 'daemon_sftp', must be bigger than or equal to 1.";
        }

        if ($this->container['daemon_listen'] === null) {
            $invalidProperties[] = "'daemon_listen' can't be null";
        }
        if (($this->container['daemon_listen'] > 65535)) {
            $invalidProperties[] = "invalid value for 'daemon_listen', must be smaller than or equal to 65535.";
        }

        if (($this->container['daemon_listen'] < 1)) {
            $invalidProperties[] = "invalid value for 'daemon_listen', must be bigger than or equal to 1.";
        }

        if ($this->container['daemon_connect'] === null) {
            $invalidProperties[] = "'daemon_connect' can't be null";
        }
        if (($this->container['daemon_connect'] > 65535)) {
            $invalidProperties[] = "invalid value for 'daemon_connect', must be smaller than or equal to 65535.";
        }

        if (($this->container['daemon_connect'] < 1)) {
            $invalidProperties[] = "invalid value for 'daemon_connect', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['upload_size']) && ($this->container['upload_size'] > 1024)) {
            $invalidProperties[] = "invalid value for 'upload_size', must be smaller than or equal to 1024.";
        }

        if (!is_null($this->container['upload_size']) && ($this->container['upload_size'] < 1)) {
            $invalidProperties[] = "invalid value for 'upload_size', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 100)) {
            throw new \InvalidArgumentException('invalid length for $name when calling StoreNodeRequest., must be smaller than or equal to 100.');
        }
        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling StoreNodeRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets public
     *
     * @return bool|null
     */
    public function getPublic()
    {
        return $this->container['public'];
    }

    /**
     * Sets public
     *
     * @param bool|null $public public
     *
     * @return self
     */
    public function setPublic($public)
    {
        if (is_null($public)) {
            throw new \InvalidArgumentException('non-nullable public cannot be null');
        }
        $this->container['public'] = $public;

        return $this;
    }

    /**
     * Gets fqdn
     *
     * @return string
     */
    public function getFqdn()
    {
        return $this->container['fqdn'];
    }

    /**
     * Sets fqdn
     *
     * @param string $fqdn fqdn
     *
     * @return self
     */
    public function setFqdn($fqdn)
    {
        if (is_null($fqdn)) {
            throw new \InvalidArgumentException('non-nullable fqdn cannot be null');
        }
        $this->container['fqdn'] = $fqdn;

        return $this;
    }

    /**
     * Gets scheme
     *
     * @return string
     */
    public function getScheme()
    {
        return $this->container['scheme'];
    }

    /**
     * Sets scheme
     *
     * @param string $scheme scheme
     *
     * @return self
     */
    public function setScheme($scheme)
    {
        if (is_null($scheme)) {
            throw new \InvalidArgumentException('non-nullable scheme cannot be null');
        }
        $allowedValues = $this->getSchemeAllowableValues();
        if (!in_array($scheme, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'scheme', must be one of '%s'",
                    $scheme,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['scheme'] = $scheme;

        return $this;
    }

    /**
     * Gets behind_proxy
     *
     * @return bool|null
     */
    public function getBehindProxy()
    {
        return $this->container['behind_proxy'];
    }

    /**
     * Sets behind_proxy
     *
     * @param bool|null $behind_proxy behind_proxy
     *
     * @return self
     */
    public function setBehindProxy($behind_proxy)
    {
        if (is_null($behind_proxy)) {
            throw new \InvalidArgumentException('non-nullable behind_proxy cannot be null');
        }
        $this->container['behind_proxy'] = $behind_proxy;

        return $this;
    }

    /**
     * Gets memory
     *
     * @return float
     */
    public function getMemory()
    {
        return $this->container['memory'];
    }

    /**
     * Sets memory
     *
     * @param float $memory memory
     *
     * @return self
     */
    public function setMemory($memory)
    {
        if (is_null($memory)) {
            throw new \InvalidArgumentException('non-nullable memory cannot be null');
        }

        if (($memory < 0)) {
            throw new \InvalidArgumentException('invalid value for $memory when calling StoreNodeRequest., must be bigger than or equal to 0.');
        }

        $this->container['memory'] = $memory;

        return $this;
    }

    /**
     * Gets memory_overallocate
     *
     * @return float
     */
    public function getMemoryOverallocate()
    {
        return $this->container['memory_overallocate'];
    }

    /**
     * Sets memory_overallocate
     *
     * @param float $memory_overallocate memory_overallocate
     *
     * @return self
     */
    public function setMemoryOverallocate($memory_overallocate)
    {
        if (is_null($memory_overallocate)) {
            throw new \InvalidArgumentException('non-nullable memory_overallocate cannot be null');
        }

        if (($memory_overallocate < -1)) {
            throw new \InvalidArgumentException('invalid value for $memory_overallocate when calling StoreNodeRequest., must be bigger than or equal to -1.');
        }

        $this->container['memory_overallocate'] = $memory_overallocate;

        return $this;
    }

    /**
     * Gets disk
     *
     * @return float
     */
    public function getDisk()
    {
        return $this->container['disk'];
    }

    /**
     * Sets disk
     *
     * @param float $disk disk
     *
     * @return self
     */
    public function setDisk($disk)
    {
        if (is_null($disk)) {
            throw new \InvalidArgumentException('non-nullable disk cannot be null');
        }

        if (($disk < 0)) {
            throw new \InvalidArgumentException('invalid value for $disk when calling StoreNodeRequest., must be bigger than or equal to 0.');
        }

        $this->container['disk'] = $disk;

        return $this;
    }

    /**
     * Gets disk_overallocate
     *
     * @return float
     */
    public function getDiskOverallocate()
    {
        return $this->container['disk_overallocate'];
    }

    /**
     * Sets disk_overallocate
     *
     * @param float $disk_overallocate disk_overallocate
     *
     * @return self
     */
    public function setDiskOverallocate($disk_overallocate)
    {
        if (is_null($disk_overallocate)) {
            throw new \InvalidArgumentException('non-nullable disk_overallocate cannot be null');
        }

        if (($disk_overallocate < -1)) {
            throw new \InvalidArgumentException('invalid value for $disk_overallocate when calling StoreNodeRequest., must be bigger than or equal to -1.');
        }

        $this->container['disk_overallocate'] = $disk_overallocate;

        return $this;
    }

    /**
     * Gets cpu
     *
     * @return float
     */
    public function getCpu()
    {
        return $this->container['cpu'];
    }

    /**
     * Sets cpu
     *
     * @param float $cpu cpu
     *
     * @return self
     */
    public function setCpu($cpu)
    {
        if (is_null($cpu)) {
            throw new \InvalidArgumentException('non-nullable cpu cannot be null');
        }

        if (($cpu < 0)) {
            throw new \InvalidArgumentException('invalid value for $cpu when calling StoreNodeRequest., must be bigger than or equal to 0.');
        }

        $this->container['cpu'] = $cpu;

        return $this;
    }

    /**
     * Gets cpu_overallocate
     *
     * @return float
     */
    public function getCpuOverallocate()
    {
        return $this->container['cpu_overallocate'];
    }

    /**
     * Sets cpu_overallocate
     *
     * @param float $cpu_overallocate cpu_overallocate
     *
     * @return self
     */
    public function setCpuOverallocate($cpu_overallocate)
    {
        if (is_null($cpu_overallocate)) {
            throw new \InvalidArgumentException('non-nullable cpu_overallocate cannot be null');
        }

        if (($cpu_overallocate < -1)) {
            throw new \InvalidArgumentException('invalid value for $cpu_overallocate when calling StoreNodeRequest., must be bigger than or equal to -1.');
        }

        $this->container['cpu_overallocate'] = $cpu_overallocate;

        return $this;
    }

    /**
     * Gets daemon_base
     *
     * @return string|null
     */
    public function getDaemonBase()
    {
        return $this->container['daemon_base'];
    }

    /**
     * Sets daemon_base
     *
     * @param string|null $daemon_base daemon_base
     *
     * @return self
     */
    public function setDaemonBase($daemon_base)
    {
        if (is_null($daemon_base)) {
            throw new \InvalidArgumentException('non-nullable daemon_base cannot be null');
        }
        $this->container['daemon_base'] = $daemon_base;

        return $this;
    }

    /**
     * Gets daemon_sftp
     *
     * @return float
     */
    public function getDaemonSftp()
    {
        return $this->container['daemon_sftp'];
    }

    /**
     * Sets daemon_sftp
     *
     * @param float $daemon_sftp daemon_sftp
     *
     * @return self
     */
    public function setDaemonSftp($daemon_sftp)
    {
        if (is_null($daemon_sftp)) {
            throw new \InvalidArgumentException('non-nullable daemon_sftp cannot be null');
        }

        if (($daemon_sftp > 65535)) {
            throw new \InvalidArgumentException('invalid value for $daemon_sftp when calling StoreNodeRequest., must be smaller than or equal to 65535.');
        }
        if (($daemon_sftp < 1)) {
            throw new \InvalidArgumentException('invalid value for $daemon_sftp when calling StoreNodeRequest., must be bigger than or equal to 1.');
        }

        $this->container['daemon_sftp'] = $daemon_sftp;

        return $this;
    }

    /**
     * Gets daemon_sftp_alias
     *
     * @return string|null
     */
    public function getDaemonSftpAlias()
    {
        return $this->container['daemon_sftp_alias'];
    }

    /**
     * Sets daemon_sftp_alias
     *
     * @param string|null $daemon_sftp_alias daemon_sftp_alias
     *
     * @return self
     */
    public function setDaemonSftpAlias($daemon_sftp_alias)
    {
        if (is_null($daemon_sftp_alias)) {
            array_push($this->openAPINullablesSetToNull, 'daemon_sftp_alias');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('daemon_sftp_alias', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['daemon_sftp_alias'] = $daemon_sftp_alias;

        return $this;
    }

    /**
     * Gets daemon_listen
     *
     * @return float
     */
    public function getDaemonListen()
    {
        return $this->container['daemon_listen'];
    }

    /**
     * Sets daemon_listen
     *
     * @param float $daemon_listen daemon_listen
     *
     * @return self
     */
    public function setDaemonListen($daemon_listen)
    {
        if (is_null($daemon_listen)) {
            throw new \InvalidArgumentException('non-nullable daemon_listen cannot be null');
        }

        if (($daemon_listen > 65535)) {
            throw new \InvalidArgumentException('invalid value for $daemon_listen when calling StoreNodeRequest., must be smaller than or equal to 65535.');
        }
        if (($daemon_listen < 1)) {
            throw new \InvalidArgumentException('invalid value for $daemon_listen when calling StoreNodeRequest., must be bigger than or equal to 1.');
        }

        $this->container['daemon_listen'] = $daemon_listen;

        return $this;
    }

    /**
     * Gets daemon_connect
     *
     * @return float
     */
    public function getDaemonConnect()
    {
        return $this->container['daemon_connect'];
    }

    /**
     * Sets daemon_connect
     *
     * @param float $daemon_connect daemon_connect
     *
     * @return self
     */
    public function setDaemonConnect($daemon_connect)
    {
        if (is_null($daemon_connect)) {
            throw new \InvalidArgumentException('non-nullable daemon_connect cannot be null');
        }

        if (($daemon_connect > 65535)) {
            throw new \InvalidArgumentException('invalid value for $daemon_connect when calling StoreNodeRequest., must be smaller than or equal to 65535.');
        }
        if (($daemon_connect < 1)) {
            throw new \InvalidArgumentException('invalid value for $daemon_connect when calling StoreNodeRequest., must be bigger than or equal to 1.');
        }

        $this->container['daemon_connect'] = $daemon_connect;

        return $this;
    }

    /**
     * Gets maintenance_mode
     *
     * @return bool|null
     */
    public function getMaintenanceMode()
    {
        return $this->container['maintenance_mode'];
    }

    /**
     * Sets maintenance_mode
     *
     * @param bool|null $maintenance_mode maintenance_mode
     *
     * @return self
     */
    public function setMaintenanceMode($maintenance_mode)
    {
        if (is_null($maintenance_mode)) {
            throw new \InvalidArgumentException('non-nullable maintenance_mode cannot be null');
        }
        $this->container['maintenance_mode'] = $maintenance_mode;

        return $this;
    }

    /**
     * Gets upload_size
     *
     * @return int|null
     */
    public function getUploadSize()
    {
        return $this->container['upload_size'];
    }

    /**
     * Sets upload_size
     *
     * @param int|null $upload_size upload_size
     *
     * @return self
     */
    public function setUploadSize($upload_size)
    {
        if (is_null($upload_size)) {
            throw new \InvalidArgumentException('non-nullable upload_size cannot be null');
        }

        if (($upload_size > 1024)) {
            throw new \InvalidArgumentException('invalid value for $upload_size when calling StoreNodeRequest., must be smaller than or equal to 1024.');
        }
        if (($upload_size < 1)) {
            throw new \InvalidArgumentException('invalid value for $upload_size when calling StoreNodeRequest., must be bigger than or equal to 1.');
        }

        $this->container['upload_size'] = $upload_size;

        return $this;
    }

    /**
     * Gets tags
     *
     * @return string[]|null
     */
    public function getTags()
    {
        return $this->container['tags'];
    }

    /**
     * Sets tags
     *
     * @param string[]|null $tags tags
     *
     * @return self
     */
    public function setTags($tags)
    {
        if (is_null($tags)) {
            throw new \InvalidArgumentException('non-nullable tags cannot be null');
        }
        $this->container['tags'] = $tags;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


