<?php
/**
 * StoreServerRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Prepaid-Host - Gameserver
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * StoreServerRequest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class StoreServerRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'StoreServerRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'external_id' => 'string',
        'name' => 'string',
        'description' => 'string',
        'user' => 'int',
        'egg' => 'int',
        'docker_image' => 'string',
        'startup' => 'string',
        'environment' => 'string[]',
        'skip_scripts' => 'bool',
        'oom_killer' => 'bool',
        'start_on_completion' => 'bool',
        'limits' => '\OpenAPI\Client\Model\StoreServerRequestLimits',
        'feature_limits' => '\OpenAPI\Client\Model\StoreServerRequestFeatureLimits',
        'allocation' => '\OpenAPI\Client\Model\StoreServerRequestAllocation',
        'deploy' => '\OpenAPI\Client\Model\StoreServerRequestDeploy'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'external_id' => null,
        'name' => null,
        'description' => null,
        'user' => null,
        'egg' => null,
        'docker_image' => null,
        'startup' => null,
        'environment' => null,
        'skip_scripts' => null,
        'oom_killer' => null,
        'start_on_completion' => null,
        'limits' => null,
        'feature_limits' => null,
        'allocation' => null,
        'deploy' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'external_id' => true,
        'name' => false,
        'description' => true,
        'user' => false,
        'egg' => false,
        'docker_image' => false,
        'startup' => false,
        'environment' => false,
        'skip_scripts' => false,
        'oom_killer' => false,
        'start_on_completion' => false,
        'limits' => false,
        'feature_limits' => false,
        'allocation' => false,
        'deploy' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'external_id' => 'external_id',
        'name' => 'name',
        'description' => 'description',
        'user' => 'user',
        'egg' => 'egg',
        'docker_image' => 'docker_image',
        'startup' => 'startup',
        'environment' => 'environment',
        'skip_scripts' => 'skip_scripts',
        'oom_killer' => 'oom_killer',
        'start_on_completion' => 'start_on_completion',
        'limits' => 'limits',
        'feature_limits' => 'feature_limits',
        'allocation' => 'allocation',
        'deploy' => 'deploy'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'external_id' => 'setExternalId',
        'name' => 'setName',
        'description' => 'setDescription',
        'user' => 'setUser',
        'egg' => 'setEgg',
        'docker_image' => 'setDockerImage',
        'startup' => 'setStartup',
        'environment' => 'setEnvironment',
        'skip_scripts' => 'setSkipScripts',
        'oom_killer' => 'setOomKiller',
        'start_on_completion' => 'setStartOnCompletion',
        'limits' => 'setLimits',
        'feature_limits' => 'setFeatureLimits',
        'allocation' => 'setAllocation',
        'deploy' => 'setDeploy'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'external_id' => 'getExternalId',
        'name' => 'getName',
        'description' => 'getDescription',
        'user' => 'getUser',
        'egg' => 'getEgg',
        'docker_image' => 'getDockerImage',
        'startup' => 'getStartup',
        'environment' => 'getEnvironment',
        'skip_scripts' => 'getSkipScripts',
        'oom_killer' => 'getOomKiller',
        'start_on_completion' => 'getStartOnCompletion',
        'limits' => 'getLimits',
        'feature_limits' => 'getFeatureLimits',
        'allocation' => 'getAllocation',
        'deploy' => 'getDeploy'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('external_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('user', $data ?? [], null);
        $this->setIfExists('egg', $data ?? [], null);
        $this->setIfExists('docker_image', $data ?? [], null);
        $this->setIfExists('startup', $data ?? [], null);
        $this->setIfExists('environment', $data ?? [], null);
        $this->setIfExists('skip_scripts', $data ?? [], null);
        $this->setIfExists('oom_killer', $data ?? [], null);
        $this->setIfExists('start_on_completion', $data ?? [], null);
        $this->setIfExists('limits', $data ?? [], null);
        $this->setIfExists('feature_limits', $data ?? [], null);
        $this->setIfExists('allocation', $data ?? [], null);
        $this->setIfExists('deploy', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['external_id']) && (mb_strlen($this->container['external_id']) > 255)) {
            $invalidProperties[] = "invalid value for 'external_id', the character length must be smaller than or equal to 255.";
        }

        if (!is_null($this->container['external_id']) && (mb_strlen($this->container['external_id']) < 1)) {
            $invalidProperties[] = "invalid value for 'external_id', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ((mb_strlen($this->container['name']) > 255)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen($this->container['name']) < 1)) {
            $invalidProperties[] = "invalid value for 'name', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['user'] === null) {
            $invalidProperties[] = "'user' can't be null";
        }
        if ($this->container['egg'] === null) {
            $invalidProperties[] = "'egg' can't be null";
        }
        if ($this->container['environment'] === null) {
            $invalidProperties[] = "'environment' can't be null";
        }
        if ($this->container['limits'] === null) {
            $invalidProperties[] = "'limits' can't be null";
        }
        if ($this->container['feature_limits'] === null) {
            $invalidProperties[] = "'feature_limits' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets external_id
     *
     * @return string|null
     */
    public function getExternalId()
    {
        return $this->container['external_id'];
    }

    /**
     * Sets external_id
     *
     * @param string|null $external_id external_id
     *
     * @return self
     */
    public function setExternalId($external_id)
    {
        if (is_null($external_id)) {
            array_push($this->openAPINullablesSetToNull, 'external_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($external_id) && (mb_strlen($external_id) > 255)) {
            throw new \InvalidArgumentException('invalid length for $external_id when calling StoreServerRequest., must be smaller than or equal to 255.');
        }
        if (!is_null($external_id) && (mb_strlen($external_id) < 1)) {
            throw new \InvalidArgumentException('invalid length for $external_id when calling StoreServerRequest., must be bigger than or equal to 1.');
        }

        $this->container['external_id'] = $external_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        if ((mb_strlen($name) > 255)) {
            throw new \InvalidArgumentException('invalid length for $name when calling StoreServerRequest., must be smaller than or equal to 255.');
        }
        if ((mb_strlen($name) < 1)) {
            throw new \InvalidArgumentException('invalid length for $name when calling StoreServerRequest., must be bigger than or equal to 1.');
        }

        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description description
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (is_null($description)) {
            array_push($this->openAPINullablesSetToNull, 'description');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('description', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets user
     *
     * @return int
     */
    public function getUser()
    {
        return $this->container['user'];
    }

    /**
     * Sets user
     *
     * @param int $user user
     *
     * @return self
     */
    public function setUser($user)
    {
        if (is_null($user)) {
            throw new \InvalidArgumentException('non-nullable user cannot be null');
        }
        $this->container['user'] = $user;

        return $this;
    }

    /**
     * Gets egg
     *
     * @return int
     */
    public function getEgg()
    {
        return $this->container['egg'];
    }

    /**
     * Sets egg
     *
     * @param int $egg egg
     *
     * @return self
     */
    public function setEgg($egg)
    {
        if (is_null($egg)) {
            throw new \InvalidArgumentException('non-nullable egg cannot be null');
        }
        $this->container['egg'] = $egg;

        return $this;
    }

    /**
     * Gets docker_image
     *
     * @return string|null
     */
    public function getDockerImage()
    {
        return $this->container['docker_image'];
    }

    /**
     * Sets docker_image
     *
     * @param string|null $docker_image docker_image
     *
     * @return self
     */
    public function setDockerImage($docker_image)
    {
        if (is_null($docker_image)) {
            throw new \InvalidArgumentException('non-nullable docker_image cannot be null');
        }
        $this->container['docker_image'] = $docker_image;

        return $this;
    }

    /**
     * Gets startup
     *
     * @return string|null
     */
    public function getStartup()
    {
        return $this->container['startup'];
    }

    /**
     * Sets startup
     *
     * @param string|null $startup startup
     *
     * @return self
     */
    public function setStartup($startup)
    {
        if (is_null($startup)) {
            throw new \InvalidArgumentException('non-nullable startup cannot be null');
        }
        $this->container['startup'] = $startup;

        return $this;
    }

    /**
     * Gets environment
     *
     * @return string[]
     */
    public function getEnvironment()
    {
        return $this->container['environment'];
    }

    /**
     * Sets environment
     *
     * @param string[] $environment environment
     *
     * @return self
     */
    public function setEnvironment($environment)
    {
        if (is_null($environment)) {
            throw new \InvalidArgumentException('non-nullable environment cannot be null');
        }
        $this->container['environment'] = $environment;

        return $this;
    }

    /**
     * Gets skip_scripts
     *
     * @return bool|null
     */
    public function getSkipScripts()
    {
        return $this->container['skip_scripts'];
    }

    /**
     * Sets skip_scripts
     *
     * @param bool|null $skip_scripts skip_scripts
     *
     * @return self
     */
    public function setSkipScripts($skip_scripts)
    {
        if (is_null($skip_scripts)) {
            throw new \InvalidArgumentException('non-nullable skip_scripts cannot be null');
        }
        $this->container['skip_scripts'] = $skip_scripts;

        return $this;
    }

    /**
     * Gets oom_killer
     *
     * @return bool|null
     */
    public function getOomKiller()
    {
        return $this->container['oom_killer'];
    }

    /**
     * Sets oom_killer
     *
     * @param bool|null $oom_killer oom_killer
     *
     * @return self
     */
    public function setOomKiller($oom_killer)
    {
        if (is_null($oom_killer)) {
            throw new \InvalidArgumentException('non-nullable oom_killer cannot be null');
        }
        $this->container['oom_killer'] = $oom_killer;

        return $this;
    }

    /**
     * Gets start_on_completion
     *
     * @return bool|null
     */
    public function getStartOnCompletion()
    {
        return $this->container['start_on_completion'];
    }

    /**
     * Sets start_on_completion
     *
     * @param bool|null $start_on_completion start_on_completion
     *
     * @return self
     */
    public function setStartOnCompletion($start_on_completion)
    {
        if (is_null($start_on_completion)) {
            throw new \InvalidArgumentException('non-nullable start_on_completion cannot be null');
        }
        $this->container['start_on_completion'] = $start_on_completion;

        return $this;
    }

    /**
     * Gets limits
     *
     * @return \OpenAPI\Client\Model\StoreServerRequestLimits
     */
    public function getLimits()
    {
        return $this->container['limits'];
    }

    /**
     * Sets limits
     *
     * @param \OpenAPI\Client\Model\StoreServerRequestLimits $limits limits
     *
     * @return self
     */
    public function setLimits($limits)
    {
        if (is_null($limits)) {
            throw new \InvalidArgumentException('non-nullable limits cannot be null');
        }
        $this->container['limits'] = $limits;

        return $this;
    }

    /**
     * Gets feature_limits
     *
     * @return \OpenAPI\Client\Model\StoreServerRequestFeatureLimits
     */
    public function getFeatureLimits()
    {
        return $this->container['feature_limits'];
    }

    /**
     * Sets feature_limits
     *
     * @param \OpenAPI\Client\Model\StoreServerRequestFeatureLimits $feature_limits feature_limits
     *
     * @return self
     */
    public function setFeatureLimits($feature_limits)
    {
        if (is_null($feature_limits)) {
            throw new \InvalidArgumentException('non-nullable feature_limits cannot be null');
        }
        $this->container['feature_limits'] = $feature_limits;

        return $this;
    }

    /**
     * Gets allocation
     *
     * @return \OpenAPI\Client\Model\StoreServerRequestAllocation|null
     */
    public function getAllocation()
    {
        return $this->container['allocation'];
    }

    /**
     * Sets allocation
     *
     * @param \OpenAPI\Client\Model\StoreServerRequestAllocation|null $allocation allocation
     *
     * @return self
     */
    public function setAllocation($allocation)
    {
        if (is_null($allocation)) {
            throw new \InvalidArgumentException('non-nullable allocation cannot be null');
        }
        $this->container['allocation'] = $allocation;

        return $this;
    }

    /**
     * Gets deploy
     *
     * @return \OpenAPI\Client\Model\StoreServerRequestDeploy|null
     */
    public function getDeploy()
    {
        return $this->container['deploy'];
    }

    /**
     * Sets deploy
     *
     * @param \OpenAPI\Client\Model\StoreServerRequestDeploy|null $deploy deploy
     *
     * @return self
     */
    public function setDeploy($deploy)
    {
        if (is_null($deploy)) {
            throw new \InvalidArgumentException('non-nullable deploy cannot be null');
        }
        $this->container['deploy'] = $deploy;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


