<?php
/**
 * MountApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Prepaid-Host - Gameserver
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.17.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MountApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MountApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for applicationMounts
     *
     * List mounts.
     *
     */
    public function testApplicationMounts()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for applicationMountsEggs
     *
     * Assign eggs to mount.
     *
     */
    public function testApplicationMountsEggs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for applicationMountsNodes
     *
     * Assign nodes to mount.
     *
     */
    public function testApplicationMountsNodes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for applicationMountsServers
     *
     * Assign servers to mount.
     *
     */
    public function testApplicationMountsServers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for applicationMountsView
     *
     * View mount.
     *
     */
    public function testApplicationMountsView()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mountDelete
     *
     * Delete mount.
     *
     */
    public function testMountDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mountDeleteEgg
     *
     * Unassign egg from mount.
     *
     */
    public function testMountDeleteEgg()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mountDeleteNode
     *
     * Unassign node from mount.
     *
     */
    public function testMountDeleteNode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mountDeleteServer
     *
     * Unassign server from mount.
     *
     */
    public function testMountDeleteServer()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mountGetEggs
     *
     * List assigned eggs.
     *
     */
    public function testMountGetEggs()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mountGetNodes
     *
     * List assigned nodes.
     *
     */
    public function testMountGetNodes()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mountGetServers
     *
     * List assigned servers.
     *
     */
    public function testMountGetServers()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mountStore
     *
     * Create mount.
     *
     */
    public function testMountStore()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for mountUpdate
     *
     * Update mount.
     *
     */
    public function testMountUpdate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
